In [3]:
# !pip install --upgrade tensorflow --quiet
# !pip install keras_tuner --quiet
# !pip install tensorflow-io --quiet
# # Google colab modules
# from google.colab import drive
import sys, importlib

# # Mount drive
# drive.mount('/content/gdrive', force_remount=True)
ROOT_PATH = './'
# sys.path.append(ROOT_PATH)

import coremlv2 as core
core._init_ml()
# core._init_models()
# core.os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# Reload coreml
importlib.reload(core)
import keras_tuner as kt

In [4]:
# Limiting GPU memory growth
gpus = core.tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            core.tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = core.tf.config.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs, ", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

1 Physical GPUs,  1 Logical GPUs


### Retrain 322/25/medium

In [10]:
model_base_id='322'
kt_iter='25'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'H:\#PROJECT\idx'
dataset_size = 'medium'
batch_size = 64
shuffle_buffer_size = 8192
retrain_epochs = 1

In [11]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load model from keras_tuner
2617/2617 [==============================] - 436s 165ms/step - loss: 0.6931 - accuracy: 0.5078 - val_loss: 0.7059 - val_accuracy: 0.5100


In [12]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 1
2617/2617 [==============================] - 520s 196ms/step - loss: 0.6927 - accuracy: 0.5296 - val_loss: 0.7059 - val_accuracy: 0.5100


In [13]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 2
2617/2617 [==============================] - 503s 190ms/step - loss: 0.6923 - accuracy: 0.5296 - val_loss: 0.7061 - val_accuracy: 0.5100


In [14]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 3
2617/2617 [==============================] - 522s 197ms/step - loss: 0.6920 - accuracy: 0.5296 - val_loss: 0.7064 - val_accuracy: 0.5100


In [15]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 4
2617/2617 [==============================] - 522s 197ms/step - loss: 0.6918 - accuracy: 0.5296 - val_loss: 0.7066 - val_accuracy: 0.5100


In [16]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 5
2617/2617 [==============================] - 554s 210ms/step - loss: 0.6916 - accuracy: 0.5296 - val_loss: 0.7063 - val_accuracy: 0.5100


In [17]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 6
2617/2617 [==============================] - 540s 205ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7077 - val_accuracy: 0.5100


In [18]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 7
2617/2617 [==============================] - 557s 211ms/step - loss: 0.6914 - accuracy: 0.5296 - val_loss: 0.7071 - val_accuracy: 0.5100


In [19]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 8
2617/2617 [==============================] - 546s 206ms/step - loss: 0.6914 - accuracy: 0.5296 - val_loss: 0.7115 - val_accuracy: 0.5100


In [20]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
1.4917624506254735e-06 32 64
Load weights from epoch 9
2617/2617 [==============================] - 525s 198ms/step - loss: 0.6914 - accuracy: 0.5296 - val_loss: 0.7072 - val_accuracy: 0.5100


### Retrain 322/25
#### full_new_wsd_mix (0.2 1 / 0 1)
1299/418/24799
1. 1479s 59ms/step - loss: 0.6585 - accuracy: 0.6049 - val_loss: 0.7045 - val_accuracy: 0.5868
2. 1511s 61ms/step - loss: 0.6510 - accuracy: 0.6109 - val_loss: 0.7984 - val_accuracy: 0.5700
3. 1513s 61ms/step - loss: 0.6482 - accuracy: 0.6130 - val_loss: 0.8451 - val_accuracy: 0.5666
4. 1538s 62ms/step - loss: 0.6466 - accuracy: 0.6145 - val_loss: 0.7499 - val_accuracy: 0.5769
5. 1511s 61ms/step - loss: 0.6453 - accuracy: 0.6158 - val_loss: 0.7638 - val_accuracy: 0.5753

In [7]:
model_base_id='322'
kt_iter='25'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'J:\#PROJECT\idx'
dataset_size = 'full_new_wsd_mix'
batch_size = 64
shuffle_buffer_size = 2048
retrain_epochs = 1
generator = True

In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 1299
Total constituents: 418
Load model from keras_tuner
24799/24799 [==============================] - 1479s 59ms/step - loss: 0.6585 - accuracy: 0.6049 - val_loss: 0.7045 - val_accuracy: 0.5868


In [9]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 1299
Total constituents: 418
Load weights from epoch 1
24799/24799 [==============================] - 1511s 61ms/step - loss: 0.6510 - accuracy: 0.6109 - val_loss: 0.7984 - val_accuracy: 0.5700


In [10]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 1299
Total constituents: 418
Load weights from epoch 2
24799/24799 [==============================] - 1513s 61ms/step - loss: 0.6482 - accuracy: 0.6130 - val_loss: 0.8451 - val_accuracy: 0.5666


In [11]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 1299
Total constituents: 418
Load weights from epoch 3
24799/24799 [==============================] - 1538s 62ms/step - loss: 0.6466 - accuracy: 0.6145 - val_loss: 0.7499 - val_accuracy: 0.5769


In [12]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 1299
Total constituents: 418
Load weights from epoch 4
24799/24799 [==============================] - 1511s 61ms/step - loss: 0.6453 - accuracy: 0.6158 - val_loss: 0.7638 - val_accuracy: 0.5753


### Retrain 325/28
#### full_new_wsd_mix (0.2 1 / 0 1)
1. 1651s 66ms/step - loss: 0.6578 - accuracy: 0.6042 - val_loss: 0.6704 - val_accuracy: 0.5878
2. 1678s 67ms/step - loss: 0.6500 - accuracy: 0.6117 - val_loss: 0.6970 - val_accuracy: 0.5831
3. 1574s 63ms/step - loss: 0.6471 - accuracy: 0.6140 - val_loss: 0.6887 - val_accuracy: 0.5837
4. 1845s 74ms/step - loss: 0.6453 - accuracy: 0.6154 - val_loss: 0.6634 - val_accuracy: 0.5865
5. 2416s 97ms/step - loss: 0.6433 - accuracy: 0.6170 - val_loss: 0.6705 - val_accuracy: 0.5762

#### full_new_wsd (0 1 / 0 1)
1. 1141s 85ms/step - loss: 0.6575 - accuracy: 0.6053 - val_loss: 0.6778 - val_accuracy: 0.5793
2. 1153s 87ms/step - loss: 0.6431 - accuracy: 0.6174 - val_loss: 0.6691 - val_accuracy: 0.5836
3. 1198s 90ms/step - loss: 0.6389 - accuracy: 0.6211 - val_loss: 0.6679 - val_accuracy: 0.5882
4. 1183s 89ms/step - loss: 0.6360 - accuracy: 0.6228 - val_loss: 0.6723 - val_accuracy: 0.5904
5. 1185s 89ms/step - loss: 0.6339 - accuracy: 0.6244 - val_loss: 0.6650 - val_accuracy: 0.5929
6. 1173s 88ms/step - loss: 0.6317 - accuracy: 0.6258 - val_loss: 0.6644 - val_accuracy: 0.5938
7. 1183s 89ms/step - loss: 0.6300 - accuracy: 0.6273 - val_loss: 0.6684 - val_accuracy: 0.5921
8. 1203s 90ms/step - loss: 0.6282 - accuracy: 0.6286 - val_loss: 0.6663 - val_accuracy: 0.5936
9. 1080s 81ms/step - loss: 0.6266 - accuracy: 0.6296 - val_loss: 0.6621 - val_accuracy: 0.5943
10.946s 71ms/step - loss: 0.6251 - accuracy: 0.6307 - val_loss: 0.6693 - val_accuracy: 0.5869
11.953s 72ms/step - loss: 0.6240 - accuracy: 0.6313 - val_loss: 0.6663 - val_accuracy: 0.5907
12.963s 72ms/step - loss: 0.6232 - accuracy: 0.6323 - val_loss: 0.6751 - val_accuracy: 0.5842
13.960s 72ms/step - loss: 0.6215 - accuracy: 0.6331 - val_loss: 0.6740 - val_accuracy: 0.5823
14.972s 73ms/step - loss: 0.6204 - accuracy: 0.6341 - val_loss: 0.6724 - val_accuracy: 0.5842
15.987s 74ms/step - loss: 0.6193 - accuracy: 0.6351 - val_loss: 0.6766 - val_accuracy: 0.5787
16.979s 73ms/step - loss: 0.6184 - accuracy: 0.6358 - val_loss: 0.6808 - val_accuracy: 0.5753
17.973s 73ms/step - loss: 0.6176 - accuracy: 0.6364 - val_loss: 0.6770 - val_accuracy: 0.5827
18.968s 73ms/step - loss: 0.6164 - accuracy: 0.6374 - val_loss: 0.6820 - val_accuracy: 0.5683
19.974s 73ms/step - loss: 0.6153 - accuracy: 0.6382 - val_loss: 0.6813 - val_accuracy: 0.5783
20.972s 73ms/step - loss: 0.6145 - accuracy: 0.6388 - val_loss: 0.6881 - val_accuracy: 0.5721

In [3]:
model_base_id='325'
kt_iter='28'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'J:\#PROJECT\idx'
dataset_size = 'full_new_wsd'
batch_size = 64
shuffle_buffer_size = 2048
retrain_epochs = 1
generator = True

In [4]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load model from keras_tuner
13240/13240 [==============================] - 1141s 85ms/step - loss: 0.6575 - accuracy: 0.6053 - val_loss: 0.6778 - val_accuracy: 0.5793


In [5]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 1
13240/13240 [==============================] - 1153s 87ms/step - loss: 0.6431 - accuracy: 0.6174 - val_loss: 0.6691 - val_accuracy: 0.5836


In [6]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 2
13240/13240 [==============================] - 1198s 90ms/step - loss: 0.6389 - accuracy: 0.6211 - val_loss: 0.6679 - val_accuracy: 0.5882


In [7]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 3
13240/13240 [==============================] - 1183s 89ms/step - loss: 0.6360 - accuracy: 0.6228 - val_loss: 0.6723 - val_accuracy: 0.5904


In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 4
13240/13240 [==============================] - 1185s 89ms/step - loss: 0.6339 - accuracy: 0.6244 - val_loss: 0.6650 - val_accuracy: 0.5929


In [9]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 5
13240/13240 [==============================] - 1173s 88ms/step - loss: 0.6317 - accuracy: 0.6258 - val_loss: 0.6644 - val_accuracy: 0.5938


In [10]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 6
13240/13240 [==============================] - 1183s 89ms/step - loss: 0.6300 - accuracy: 0.6273 - val_loss: 0.6684 - val_accuracy: 0.5921


In [11]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 7
13240/13240 [==============================] - 1203s 90ms/step - loss: 0.6282 - accuracy: 0.6286 - val_loss: 0.6663 - val_accuracy: 0.5936


In [12]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 8
13240/13240 [==============================] - 1080s 81ms/step - loss: 0.6266 - accuracy: 0.6296 - val_loss: 0.6621 - val_accuracy: 0.5943


In [13]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 9
13240/13240 [==============================] - 946s 71ms/step - loss: 0.6251 - accuracy: 0.6307 - val_loss: 0.6693 - val_accuracy: 0.5869


In [14]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 10
13240/13240 [==============================] - 953s 72ms/step - loss: 0.6240 - accuracy: 0.6313 - val_loss: 0.6663 - val_accuracy: 0.5907


In [15]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 11
13240/13240 [==============================] - 963s 72ms/step - loss: 0.6232 - accuracy: 0.6323 - val_loss: 0.6751 - val_accuracy: 0.5842


In [16]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 12
13240/13240 [==============================] - 960s 72ms/step - loss: 0.6215 - accuracy: 0.6331 - val_loss: 0.6740 - val_accuracy: 0.5823


In [17]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 13
13240/13240 [==============================] - 972s 73ms/step - loss: 0.6204 - accuracy: 0.6341 - val_loss: 0.6724 - val_accuracy: 0.5842


In [18]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 14
13240/13240 [==============================] - 987s 74ms/step - loss: 0.6193 - accuracy: 0.6351 - val_loss: 0.6766 - val_accuracy: 0.5787


In [19]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 15
13240/13240 [==============================] - 979s 73ms/step - loss: 0.6184 - accuracy: 0.6358 - val_loss: 0.6808 - val_accuracy: 0.5753


In [20]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 16
13240/13240 [==============================] - 973s 73ms/step - loss: 0.6176 - accuracy: 0.6364 - val_loss: 0.6770 - val_accuracy: 0.5827


In [21]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 17
13240/13240 [==============================] - 968s 73ms/step - loss: 0.6164 - accuracy: 0.6374 - val_loss: 0.6820 - val_accuracy: 0.5683


In [22]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 18
13240/13240 [==============================] - 974s 73ms/step - loss: 0.6153 - accuracy: 0.6382 - val_loss: 0.6813 - val_accuracy: 0.5783


In [23]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 19
13240/13240 [==============================] - 972s 73ms/step - loss: 0.6145 - accuracy: 0.6388 - val_loss: 0.6881 - val_accuracy: 0.5721


### Manually retrain model

In [5]:
model_base_id = '327'
version = '0'
model_no = model_base_id
constituent_limits = 0.05
id_constituent = 1
min_vid_constituents = 0.2
epochs = 40
iter_id = f'model-{model_no}-{version}_constituent_limits-{constituent_limits}_id_constituent-{id_constituent}_min_vid_constituents-{min_vid_constituents}_epochs-{epochs}'
ROOT_PATH='./'
DB_ROOT_PATH='J:\#PROJECT\idx'
db_ver = '8'
batch_size = 1024
shuffle_buffer_size = 16
generator=True

In [ ]:
# Train: `slice_from_beginning`=True
train_gen = core.load_dataset_wsd(slice_from_beginning=True, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, constituent_limits=constituent_limits, id_constituent=id_constituent, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)
# Validation: `slice_from_beginning`=False. constituent_limits in validation is always 0 (focus on idx performance progression only)
validation_gen = core.load_dataset_wsd(slice_from_beginning=False, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, constituent_limits=0, id_constituent=id_constituent, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)

# Load model backbone
model = core.model_switcher_preloaded(model_no, version=version)
history = model.fit(train_gen, validation_data=validation_gen, epochs=epochs, verbose=1)

save_path = core.os.path.join(ROOT_PATH, f'models/preloaded/{iter_id}/')
model.save_weights(f'{save_path}/weights/checkpoint')
model.save(f'{save_path}/model')

history.history['batch_size'] = batch_size
history.history['shuffle_buffer_size'] = shuffle_buffer_size

with open(f'{save_path}/history.json', 'w') as f:
    core.json.dump(history.history, f)

Total constituents: 1894
Total constituents: 422
Epoch 1/40
1652/1652 [==============================] - 1464s 870ms/step - loss: 0.6682 - accuracy: 0.5899 - val_loss: 0.6576 - val_accuracy: 0.5997
Epoch 2/40
1652/1652 [==============================] - 1536s 916ms/step - loss: 0.6581 - accuracy: 0.6061 - val_loss: 0.6531 - val_accuracy: 0.6078
Epoch 3/40
1652/1652 [==============================] - 1503s 899ms/step - loss: 0.6557 - accuracy: 0.6090 - val_loss: 0.6518 - val_accuracy: 0.6101
Epoch 4/40
1652/1652 [==============================] - 1525s 911ms/step - loss: 0.6533 - accuracy: 0.6113 - val_loss: 0.6504 - val_accuracy: 0.6106
Epoch 5/40
1652/1652 [==============================] - 1506s 901ms/step - loss: 0.6507 - accuracy: 0.6136 - val_loss: 0.6541 - val_accuracy: 0.6080
Epoch 6/40
1652/1652 [==============================] - 1522s 910ms/step - loss: 0.6485 - accuracy: 0.6153 - val_loss: 0.6674 - val_accuracy: 0.5984
Epoch 7/40
1652/1652 [==============================] - 1