In [8]:
# !pip install --upgrade tensorflow --quiet
# !pip install keras_tuner --quiet
# !pip install tensorflow-io --quiet
# # Google colab modules
# from google.colab import drive
import sys, importlib

# # Mount drive
# drive.mount('/content/gdrive', force_remount=True)
ROOT_PATH = './'
# sys.path.append(ROOT_PATH)

import coremlv2 as core
core._init_ml()
# core._init_models()
# core.os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# Reload coreml
importlib.reload(core)
import keras_tuner as kt

In [9]:
# Limiting GPU memory growth
gpus = core.tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            core.tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = core.tf.config.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs, ", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

1 Physical GPUs,  1 Logical GPUs


### v16-merged-shuffled-val_loss-32 whole data 650
Target: 100 epochs, 1 epochs/session

In [2]:
model_base_id = '314'
model_source = ['BBCA']
model_ticker_target = ['MERGED-shuffled']
shift = 0
interval = 1
recurrent = 120
db_ver = '4'
dataset_ver = '1'
kt_iter = '16'
split = 0.8
retrain = True
primary_metrics = 'val_loss'
ascending = True
verbose = 1
generator = True
batch_size = 32
retrain_epochs = 1
backtest = False

# Load, retrain, and save model
model, data_version = core.read_best_model(model_base_id, model_source, model_ticker_target, shift, interval, recurrent, db_ver, dataset_ver, kt_iter, split, ROOT_PATH=ROOT_PATH, retrain=retrain, primary_metrics=primary_metrics, ascending=ascending, verbose=verbose, generator=generator, batch_size=batch_size, retrain_epochs=retrain_epochs, backtest=backtest)

Total params: 402219
Load model from keras_tuner
46562/46562 [==============================] - 32163s 661ms/step - loss: 0.6917 - accuracy: 0.5306 - val_loss: 0.6872 - val_accuracy: 0.5558


In [3]:
model_base_id = '314'
model_source = ['BBCA']
model_ticker_target = ['MERGED-shuffled']
shift = 0
interval = 1
recurrent = 120
db_ver = '4'
dataset_ver = '1'
kt_iter = '16'
split = 0.8
retrain = True
primary_metrics = 'val_loss'
ascending = True
verbose = 1
generator = True
batch_size = 32
retrain_epochs = 1
backtest = False

# Load, retrain, and save model
model, data_version = core.read_best_model(model_base_id, model_source, model_ticker_target, shift, interval, recurrent, db_ver, dataset_ver, kt_iter, split, ROOT_PATH=ROOT_PATH, retrain=retrain, primary_metrics=primary_metrics, ascending=ascending, verbose=verbose, generator=generator, batch_size=batch_size, retrain_epochs=retrain_epochs, backtest=backtest)

Total params: 402219
Load weights from epoch 1
46562/46562 [==============================] - 47909s 999ms/step - loss: 0.6900 - accuracy: 0.5405 - val_loss: 0.6861 - val_accuracy: 0.5558


In [ ]:
model_base_id = '314'
model_source = ['BBCA']
model_ticker_target = ['MERGED-shuffled']
shift = 0
interval = 1
recurrent = 120
db_ver = '4'
dataset_ver = '1'
kt_iter = '16'
split = 0.8
retrain = True
primary_metrics = 'val_loss'
ascending = True
verbose = 1
generator = True
batch_size = 32
retrain_epochs = 1
backtest = False

# Load, retrain, and save model
model, data_version = core.read_best_model(model_base_id, model_source, model_ticker_target, shift, interval, recurrent, db_ver, dataset_ver, kt_iter, split, ROOT_PATH=ROOT_PATH, retrain=retrain, primary_metrics=primary_metrics, ascending=ascending, verbose=verbose, generator=generator, batch_size=batch_size, retrain_epochs=retrain_epochs, backtest=backtest)

Total params: 402219
Load weights from epoch 2
   2445/Unknown - 27544s 10s/step - loss: 0.6910 - accuracy: 0.5341

### Retrain 321/23
#### full_new_wsd (0 1 / 0 1)
418/418/13240
1. 614s 46ms/step - loss: 0.6543 - accuracy: 0.6112 - val_loss: 0.6797 - val_accuracy: 0.5847
2. 601s 45ms/step - loss: 0.6438 - accuracy: 0.6174 - val_loss: 0.6732 - val_accuracy: 0.5857
3. 709s 53ms/step - loss: 0.6408 - accuracy: 0.6193 - val_loss: 0.6704 - val_accuracy: 0.5870
4. 772s 58ms/step - loss: 0.6392 - accuracy: 0.6204 - val_loss: 0.6706 - val_accuracy: 0.5876
5. 705s 53ms/step - loss: 0.6378 - accuracy: 0.6217 - val_loss: 0.6699 - val_accuracy: 0.5871
6. 691s 52ms/step - loss: 0.6361 - accuracy: 0.6228 - val_loss: 0.6663 - val_accuracy: 0.5888
7. 791s 60ms/step - loss: 0.6350 - accuracy: 0.6233 - val_loss: 0.6672 - val_accuracy: 0.5887
8. 915s 69ms/step - loss: 0.6337 - accuracy: 0.6242 - val_loss: 0.6679 - val_accuracy: 0.5883
9. 912s 69ms/step - loss: 0.6327 - accuracy: 0.6250 - val_loss: 0.6642 - val_accuracy: 0.5900
10.769s 58ms/step - loss: 0.6318 - accuracy: 0.6257 - val_loss: 0.6670 - val_accuracy: 0.5898
11.715s 54ms/step - loss: 0.6308 - accuracy: 0.6266 - val_loss: 0.6639 - val_accuracy: 0.5907
12.710s 53ms/step - loss: 0.6298 - accuracy: 0.6270 - val_loss: 0.6665 - val_accuracy: 0.5889
13.698s 53ms/step - loss: 0.6292 - accuracy: 0.6276 - val_loss: 0.6646 - val_accuracy: 0.5901
14.707s 53ms/step - loss: 0.6283 - accuracy: 0.6282 - val_loss: 0.6657 - val_accuracy: 0.5893
15.716s 54ms/step - loss: 0.6274 - accuracy: 0.6284 - val_loss: 0.6650 - val_accuracy: 0.5898
16.734s 55ms/step - loss: 0.6266 - accuracy: 0.6292 - val_loss: 0.6668 - val_accuracy: 0.5895
17.714s 54ms/step - loss: 0.6260 - accuracy: 0.6297 - val_loss: 0.6669 - val_accuracy: 0.5900
18.705s 53ms/step - loss: 0.6251 - accuracy: 0.6305 - val_loss: 0.6655 - val_accuracy: 0.5903
19.824s 62ms/step - loss: 0.6244 - accuracy: 0.6310 - val_loss: 0.6637 - val_accuracy: 0.5916
20.817s 61ms/step - loss: 0.6238 - accuracy: 0.6313 - val_loss: 0.6669 - val_accuracy: 0.5886

In [3]:
model_base_id='321'
kt_iter='23'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'J:\#PROJECT\idx'
dataset_size = 'full_new_wsd'
batch_size = 64
shuffle_buffer_size = 2048
retrain_epochs = 1
generator = True

In [4]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load model from keras_tuner
13240/13240 [==============================] - 614s 46ms/step - loss: 0.6543 - accuracy: 0.6112 - val_loss: 0.6797 - val_accuracy: 0.5847


In [5]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 1
13240/13240 [==============================] - 601s 45ms/step - loss: 0.6438 - accuracy: 0.6174 - val_loss: 0.6732 - val_accuracy: 0.5857


In [6]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 2
13240/13240 [==============================] - 709s 53ms/step - loss: 0.6408 - accuracy: 0.6193 - val_loss: 0.6704 - val_accuracy: 0.5870


In [7]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 3
13240/13240 [==============================] - 772s 58ms/step - loss: 0.6392 - accuracy: 0.6204 - val_loss: 0.6706 - val_accuracy: 0.5876


In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 4
13240/13240 [==============================] - 705s 53ms/step - loss: 0.6378 - accuracy: 0.6217 - val_loss: 0.6699 - val_accuracy: 0.5871


In [4]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 5
13240/13240 [==============================] - 691s 52ms/step - loss: 0.6361 - accuracy: 0.6228 - val_loss: 0.6663 - val_accuracy: 0.5888


In [5]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 6
13240/13240 [==============================] - 791s 60ms/step - loss: 0.6350 - accuracy: 0.6233 - val_loss: 0.6672 - val_accuracy: 0.5887


In [6]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 7
13240/13240 [==============================] - 915s 69ms/step - loss: 0.6337 - accuracy: 0.6242 - val_loss: 0.6679 - val_accuracy: 0.5883


In [7]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 8
13240/13240 [==============================] - 912s 69ms/step - loss: 0.6327 - accuracy: 0.6250 - val_loss: 0.6642 - val_accuracy: 0.5900


In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 9
13240/13240 [==============================] - 769s 58ms/step - loss: 0.6318 - accuracy: 0.6257 - val_loss: 0.6670 - val_accuracy: 0.5898


In [9]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 10
13240/13240 [==============================] - 715s 54ms/step - loss: 0.6308 - accuracy: 0.6266 - val_loss: 0.6639 - val_accuracy: 0.5907


In [10]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 11
13240/13240 [==============================] - 710s 53ms/step - loss: 0.6298 - accuracy: 0.6270 - val_loss: 0.6665 - val_accuracy: 0.5889


In [11]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 12
13240/13240 [==============================] - 698s 53ms/step - loss: 0.6292 - accuracy: 0.6276 - val_loss: 0.6646 - val_accuracy: 0.5901


In [12]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 13
13240/13240 [==============================] - 707s 53ms/step - loss: 0.6283 - accuracy: 0.6282 - val_loss: 0.6657 - val_accuracy: 0.5893


In [13]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 14
13240/13240 [==============================] - 716s 54ms/step - loss: 0.6274 - accuracy: 0.6284 - val_loss: 0.6650 - val_accuracy: 0.5898


In [14]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 15
13240/13240 [==============================] - 734s 55ms/step - loss: 0.6266 - accuracy: 0.6292 - val_loss: 0.6668 - val_accuracy: 0.5895


In [15]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 16
13240/13240 [==============================] - 714s 54ms/step - loss: 0.6260 - accuracy: 0.6297 - val_loss: 0.6669 - val_accuracy: 0.5900


In [16]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 17
13240/13240 [==============================] - 705s 53ms/step - loss: 0.6251 - accuracy: 0.6305 - val_loss: 0.6655 - val_accuracy: 0.5903


In [17]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 18
13240/13240 [==============================] - 824s 62ms/step - loss: 0.6244 - accuracy: 0.6310 - val_loss: 0.6637 - val_accuracy: 0.5916


In [18]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 418
Total constituents: 418
Load weights from epoch 19
13240/13240 [==============================] - 817s 61ms/step - loss: 0.6238 - accuracy: 0.6313 - val_loss: 0.6669 - val_accuracy: 0.5886


### Retrain 324/27
#### full_new_wsd_mix (0.2 1 / 0 1)
1299/418/24799
1. 1763s 71ms/step - loss: 0.6576 - accuracy: 0.6051 - val_loss: 0.6709 - val_accuracy: 0.5899
2. 1853s 74ms/step - loss: 0.6496 - accuracy: 0.6125 - val_loss: 0.6717 - val_accuracy: 0.5898
3. 1883s 76ms/step - loss: 0.6464 - accuracy: 0.6143 - val_loss: 0.7009 - val_accuracy: 0.5820
4. 1703s 68ms/step - loss: 0.6443 - accuracy: 0.6162 - val_loss: 0.6682 - val_accuracy: 0.5901
5. 1738s 70ms/step - loss: 0.6424 - accuracy: 0.6177 - val_loss: 0.6717 - val_accuracy: 0.5879

#### full_new_wsd (0 1 / 0 1)
418/418/13240(64)
1. 1196s 90ms/step - loss: 0.6563 - accuracy: 0.6068 - val_loss: 0.6570 - val_accuracy: 0.5942
2. 1187s 89ms/step - loss: 0.6424 - accuracy: 0.6178 - val_loss: 0.6588 - val_accuracy: 0.5942
3. 1189s 89ms/step - loss: 0.6381 - accuracy: 0.6211 - val_loss: 0.6641 - val_accuracy: 0.5927
4. 1203s 90ms/step - loss: 0.6352 - accuracy: 0.6237 - val_loss: 0.6666 - val_accuracy: 0.5911
5. 1176s 88ms/step - loss: 0.6328 - accuracy: 0.6252 - val_loss: 0.6690 - val_accuracy: 0.5904
6. 1168s 88ms/step - loss: 0.6309 - accuracy: 0.6269 - val_loss: 0.6711 - val_accuracy: 0.5856
7. 1175s 88ms/step - loss: 0.6287 - accuracy: 0.6286 - val_loss: 0.6672 - val_accuracy: 0.5884
8. 947s 71ms/step - loss: 0.6269 - accuracy: 0.6297 - val_loss: 0.6689 - val_accuracy: 0.5871
9. 866s 65ms/step - loss: 0.6253 - accuracy: 0.6306 - val_loss: 0.6740 - val_accuracy: 0.5874
10.871s 65ms/step - loss: 0.6238 - accuracy: 0.6319 - val_loss: 0.6775 - val_accuracy: 0.5874
11.882s 66ms/step - loss: 0.6223 - accuracy: 0.6331 - val_loss: 0.6891 - val_accuracy: 0.5794
12.885s 66ms/step - loss: 0.6210 - accuracy: 0.6338 - val_loss: 0.6803 - val_accuracy: 0.5801
13.911s 68ms/step - loss: 0.6197 - accuracy: 0.6355 - val_loss: 0.6770 - val_accuracy: 0.5820
14.913s 69ms/step - loss: 0.6185 - accuracy: 0.6363 - val_loss: 0.6769 - val_accuracy: 0.5837
15.877s 66ms/step - loss: 0.6176 - accuracy: 0.6370 - val_loss: 0.6779 - val_accuracy: 0.5830
16.883s 66ms/step - loss: 0.6164 - accuracy: 0.6380 - val_loss: 0.6838 - val_accuracy: 0.5793
17.881s 66ms/step - loss: 0.6157 - accuracy: 0.6385 - val_loss: 0.6810 - val_accuracy: 0.5800
18.885s 66ms/step - loss: 0.6145 - accuracy: 0.6396 - val_loss: 0.6868 - val_accuracy: 0.5764
19.894s 67ms/step - loss: 0.6133 - accuracy: 0.6407 - val_loss: 0.6881 - val_accuracy: 0.5769
20.887s 67ms/step - loss: 0.6121 - accuracy: 0.6415 - val_loss: 0.6847 - val_accuracy: 0.5771

### Retrain 326/32
#### full_new_wsd (0 1 / 0 1)

In [2]:
model_base_id='326'
kt_iter='32'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'J:\#PROJECT\idx'
dataset_size = 'full_new_wsd'
batch_size = 64
shuffle_buffer_size = 2048
retrain_epochs = 1
generator = False

In [3]:
# 20
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

Total constituents: 423
Total constituents: 423
Load model from keras_tuner
5416/5416 [==============================] - 143s 25ms/step - loss: 0.6543 - accuracy: 0.5897 - val_loss: 0.6371 - val_accuracy: 0.6108
Total constituents: 423
Total constituents: 423
Load weights from epoch 1


InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

In [ ]:
# 40
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

In [ ]:
# 60
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

In [ ]:
# 80
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

In [ ]:
# 100
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs, generator=generator)

### Load and evaluate existing model to predict idx data and find where the ticker would produce nan_loss

In [5]:
ROOT_PATH = './'
kt_iter = '23'

base_path = os.path.join(ROOT_PATH, 'models/kt/', f'v{kt_iter}/')
last_epochs = core.last_epochs_from_directory(base_path, 'wsd')
model_source_path = core.os.path.join(base_path, 'wsd/')
best_model = core.best_model_metadata(model_source_path, metrics=['val_loss','val_accuracy'], primary_metrics='val_loss', ascending=True)
model = core.model_switcher_kt_build(model_base_id, core.hp_params(best_model), 0, 0)
model.load_weights(os.path.join(base_path, f'wsd_retrain-epochs{last_epochs}/weights/checkpoint'))

In [21]:
# Load idx data
base_idx = 'J:\\#PROJECT\\idx\\db\\v8\\dataset\\vid'
idx_listdir = core.os.listdir(base_idx)
suffix = '_shift0_interval5_recurrent120_split0.8.hdf5'
selected_ticker = 'BBRI.JK'
selected_ticker_path = core.os.path.join(base_idx, selected_ticker + suffix)

In [31]:
for file in idx_listdir:
    selected_ticker_path = core.os.path.join(base_idx, file)
    with core.h5py.File(selected_ticker_path, 'r') as f:
        inputs = f['test_inputs'][()]
        labels = f['test_labels'][()]
    history = model.evaluate(inputs, labels, verbose=0)
    print(file.split('_')[0] + f' {history[0]}')

AALI.JK nan
ABBA.JK nan
ABDA.JK nan
ABMM.JK nan
ACES.JK nan
ACST.JK nan
ADES.JK nan
ADHI.JK nan
ADMF.JK nan
ADMG.JK nan
ADRO.JK nan
AGII.JK nan
AGRO.JK nan
AGRS.JK nan
AHAP.JK nan
AIMS.JK nan
AISA.JK nan
AKKU.JK nan
AKPI.JK nan
AKRA.JK nan
AKSI.JK nan
ALDO.JK nan
ALKA.JK nan
ALMI.JK nan
ALTO.JK nan
AMAG.JK nan
AMFG.JK nan
AMIN.JK nan
AMRT.JK nan
ANDI.JK nan
ANJT.JK nan
ANTM.JK nan
APEX.JK nan
APIC.JK nan
APII.JK nan
APLI.JK nan
APLN.JK nan
ARGO.JK nan
ARII.JK nan
ARKA.JK nan
ARNA.JK nan
ARTA.JK nan
ARTO.JK nan
ASBI.JK nan
ASDM.JK nan
ASGR.JK nan
ASII.JK nan
ASJT.JK nan
ASMI.JK nan
ASRI.JK nan
ASRM.JK nan
ASSA.JK nan
ATIC.JK nan
AUTO.JK nan
BABP.JK nan
BACA.JK nan
BAJA.JK nan
BALI.JK nan
BAPA.JK nan
BATA.JK nan
BAYU.JK nan
BBCA.JK nan
BBHI.JK nan
BBKP.JK nan
BBLD.JK nan
BBMD.JK nan
BBNI.JK nan
BBRI.JK nan
BBRM.JK nan
BBTN.JK nan
BBYB.JK nan
BCAP.JK nan
BCIC.JK nan
BCIP.JK nan
BDMN.JK nan
BEEF.JK nan
BEKS.JK nan
BELL.JK nan
BEST.JK nan
BFIN.JK nan
BGTG.JK nan
BHIT.JK nan
BIKA.JK nan
BIMA

In [30]:
idx_listdir[0].split('_')[0]

'AALI.JK'

In [28]:
history[0]

nan

In [6]:
model_no = model_base_id
train_gen = core.load_dataset_wsd_traintest(subset='training', dataset_size=dataset_size, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)

validation_gen = core.load_dataset_wsd_traintest(subset='validation', dataset_size=dataset_size, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)

Total constituents: 396
Total constituents: 396


In [8]:
base_path = core.os.path.join(ROOT_PATH, 'models/kt/', f'v{kt_iter}/')

last_epochs = core.last_epochs_from_directory(base_path, 'wsd')

# Load model backbone
model_source_path = core.os.path.join(base_path, 'wsd/')
best_model = core.best_model_metadata(model_source_path, metrics=['val_loss','val_accuracy'], primary_metrics='val_loss', ascending=True)

model = core.model_switcher_kt_build(model_base_id, core.hp_params(best_model), 0, 0)

if last_epochs == 0:
    print('Load model from keras_tuner')
    # Load weights from keras_tuner directory
    model.load_weights(core.os.path.join(model_source_path, f'{best_model.id}/', 'checkpoints/epoch_0/checkpoint'))
    # If have been trained before, continue training for last epoch
elif last_epochs > 0:
    print(f'Load weights from epoch {last_epochs}')
    # Load weights from previously trained model
    model.load_weights(core.os.path.join(base_path, f'wsd_retrain-epochs{last_epochs}/weights/checkpoint'))

Load model from keras_tuner


In [9]:
if generator:
    model.fit(train_gen, validation_data=validation_gen, epochs=retrain_epochs, verbose=1)
elif not generator:
    train_inputs, train_labels = train_gen
    validation_inputs, validation_labels = validation_gen
    model.fit(train_inputs, train_labels, validation_data=(validation_inputs, validation_labels), epochs=retrain_epochs, verbose=1)

3551/3551 [==============================] - 91s 24ms/step - loss: 0.6689 - accuracy: 0.5879 - val_loss: nan - val_accuracy: 0.5114


In [6]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 3114
Total constituents: 362
Load weights from epoch 1
15688/15688 [==============================] - 1108s 70ms/step - loss: 0.6582 - accuracy: 0.6056 - val_loss: nan - val_accuracy: 0.5088


In [7]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 3114
Total constituents: 362
Load weights from epoch 2
15688/15688 [==============================] - 1048s 67ms/step - loss: 0.6572 - accuracy: 0.6064 - val_loss: nan - val_accuracy: 0.5088


In [ ]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 3114
Total constituents: 362
Load weights from epoch 3
   8336/Unknown - 559s 67ms/step - loss: 0.6561 - accuracy: 0.6081

In [ ]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 5
2617/2617 [==============================] - 264s 100ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7325 - val_accuracy: 0.5020


In [9]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 6
2617/2617 [==============================] - 272s 102ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7348 - val_accuracy: 0.5020


In [10]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 7
2617/2617 [==============================] - 271s 102ms/step - loss: 0.6916 - accuracy: 0.5296 - val_loss: 0.7354 - val_accuracy: 0.5057


In [3]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 8
2617/2617 [==============================] - 227s 86ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7353 - val_accuracy: 0.5057


In [4]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 9
2617/2617 [==============================] - 247s 93ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7373 - val_accuracy: 0.5057


### Retrain 323/26/medium

In [6]:
model_base_id='323'
kt_iter='26'
db_ver='8'
ROOT_PATH = './'
DB_ROOT_PATH = 'H:\#PROJECT\idx'
dataset_size = 'medium'
batch_size = 64
shuffle_buffer_size = 8192
retrain_epochs = 1

In [7]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load model from keras_tuner
2617/2617 [==============================] - 1029s 390ms/step - loss: 0.6927 - accuracy: 0.5251 - val_loss: 0.7218 - val_accuracy: 0.4943


In [8]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 1
2617/2617 [==============================] - 1033s 392ms/step - loss: 0.6921 - accuracy: 0.5296 - val_loss: 0.7202 - val_accuracy: 0.4943


In [9]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 2
2617/2617 [==============================] - 1082s 411ms/step - loss: 0.6917 - accuracy: 0.5296 - val_loss: 0.7163 - val_accuracy: 0.4924


In [10]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 3
2617/2617 [==============================] - 1025s 389ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7029 - val_accuracy: 0.4924


In [11]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 4
2617/2617 [==============================] - 1029s 391ms/step - loss: 0.6914 - accuracy: 0.5296 - val_loss: 0.7019 - val_accuracy: 0.4924


In [12]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 5
2617/2617 [==============================] - 1004s 381ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.6991 - val_accuracy: 0.4924


In [13]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 6
2617/2617 [==============================] - 1023s 389ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7078 - val_accuracy: 0.4924


In [14]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 7
2617/2617 [==============================] - 1007s 382ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7030 - val_accuracy: 0.4924


In [15]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 8
2617/2617 [==============================] - 1048s 398ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7124 - val_accuracy: 0.4924


In [16]:
core.retrain_model(model_base_id, kt_iter, db_ver, ROOT_PATH=ROOT_PATH, DB_ROOT_PATH=DB_ROOT_PATH, dataset_size=dataset_size, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, retrain_epochs=retrain_epochs)

Total constituents: 298
Total constituents: 123
Load weights from epoch 9
2617/2617 [==============================] - 1111s 422ms/step - loss: 0.6915 - accuracy: 0.5296 - val_loss: 0.7168 - val_accuracy: 0.4924


### Manually retrain model

In [23]:
model_base_id = '327'
version = '0'
model_no = model_base_id
constituent_limits = 0.025
id_constituent = 1
min_vid_constituents = 0.2
epochs = 40
iter_id = f'model-{model_no}-{version}_constituent_limits-{constituent_limits}_id_constituent-{id_constituent}_min_vid_constituents-{min_vid_constituents}_epochs-{epochs}'
ROOT_PATH='./'
DB_ROOT_PATH='J:\#PROJECT\idx'
db_ver = '8'
batch_size = 1024
shuffle_buffer_size = 16
generator=True

In [24]:
# Train: `slice_from_beginning`=True
train_gen = core.load_dataset_wsd(slice_from_beginning=True, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, constituent_limits=constituent_limits, id_constituent=id_constituent, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)
# Validation: `slice_from_beginning`=False. constituent_limits in validation is always 0 (focus on idx performance progression only)
validation_gen = core.load_dataset_wsd(slice_from_beginning=False, ROOT_PATH=DB_ROOT_PATH, db_ver=db_ver, constituent_limits=0, id_constituent=id_constituent, batch_size=batch_size, shuffle_buffer_size=shuffle_buffer_size, seed=0, generator=generator, model_no=model_no)

# Load model backbone
model = core.model_switcher_preloaded(model_no, version=version)
history = model.fit(train_gen, validation_data=validation_gen, epochs=epochs, verbose=1)

save_path = core.os.path.join(ROOT_PATH, f'models/preloaded/{iter_id}/')
model.save_weights(f'{save_path}/weights/checkpoint')
model.save(f'{save_path}/model')

history.history['batch_size'] = batch_size
history.history['shuffle_buffer_size'] = shuffle_buffer_size

with open(f'{save_path}/history.json', 'w') as f:
    core.json.dump(history.history, f)

Total constituents: 1149
Total constituents: 422
Epoch 1/40
1220/1220 [==============================] - 899s 723ms/step - loss: 0.6724 - accuracy: 0.5830 - val_loss: 0.6581 - val_accuracy: 0.6007
Epoch 2/40
1220/1220 [==============================] - 911s 737ms/step - loss: 0.6582 - accuracy: 0.6053 - val_loss: 0.6541 - val_accuracy: 0.6070
Epoch 3/40
1220/1220 [==============================] - 932s 754ms/step - loss: 0.6549 - accuracy: 0.6100 - val_loss: 0.6533 - val_accuracy: 0.6068
Epoch 4/40
1220/1220 [==============================] - 952s 770ms/step - loss: 0.6520 - accuracy: 0.6130 - val_loss: 0.6520 - val_accuracy: 0.6040
Epoch 5/40
1220/1220 [==============================] - 929s 751ms/step - loss: 0.6494 - accuracy: 0.6152 - val_loss: 0.6492 - val_accuracy: 0.6070
Epoch 6/40
1220/1220 [==============================] - 940s 761ms/step - loss: 0.6461 - accuracy: 0.6175 - val_loss: 0.6492 - val_accuracy: 0.6084
Epoch 7/40
1220/1220 [==============================] - 934s 75